# Generated by Django 3.0.6 on 2020-06-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('link', models.URLField()),
                ('viewed', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
    ]
