# Generated by Django 3.0.6 on 2020-06-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed_items', '0001_initial'),
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feeds.Feed'),
        ),
        migrations.AlterUniqueTogether(
            name='feeditem',
            unique_together={('feed', 'guid')},
        ),
    ]
