# Generated by Django 3.0.7 on 2020-06-14 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed_items', '0001_initial'),
        ('feeds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feeds.Feed'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='feed_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to='feed_items.FeedItem'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='feed_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed_items.FeedItem'),
        ),
        migrations.AlterUniqueTogether(
            name='feeditem',
            unique_together={('feed', 'guid')},
        ),
    ]
