# Generated by Django 3.0.6 on 2020-06-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed_items', '0002_auto_20200605_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed_items.FeedItem')),
            ],
        ),
    ]
