version: "3.7"

services:
  db:
    image: postgres
    expose:
      - 5432
    volumes:
    - pg_data:/var/lib/postgresql/data
    env_file:
      - development.env

  web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    env_file:
      - development.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery_worker
      - celery_beat
      - memcached

  celery_worker:
    build: .
    volumes:
      - .:/code
    command: celery -A sendcloud worker -l info
    env_file:
      - development.env
    depends_on:
      - db
      - rabbitmq

  celery_beat:
    build: .
    volumes:
      - .:/code
    command: celery -A sendcloud beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - development.env
    depends_on:
      - db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq1
    env_file:
      - development.env
    ports:
      - "5672:5672"
      - "15672:15672"
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

volumes:
  pg_data:
