# Generated by Django 3.0.6 on 2020-06-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='fetcher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.PeriodicTask'),
        ),
    ]
